# Set Fish as the default shell
set-option -g default-shell /opt/homebrew/bin/fish
# Source Fish configuration
set-option -g default-command "fish -c 'source ~/.config/fish/config.fish; fish'"

# improve colors
set -g default-terminal 'screen-256color'
set -sa terminal-features ',xterm-kitty:RGB'

set -gq allow-passthrough on

set -g mouse on

# set the escape time to a low value, fix neovim `ESC` delay problem
set -g escape-time 10

# Border lines between panes are thicker
# single -> single lines using ACS or UTF-8 characters
# double -> double lines using UTF-8 characters
# heavy  -> heavy lines using UTF-8 characters
# simple -> simple ASCII characters
# number -> the pane number
set -g pane-border-lines single

# Indicate active pane by colouring only half of the border in windows with
# exactly two panes, by displaying arrow markers, by drawing both or neither.
# [off | colour | arrows | both]
set -g pane-border-indicators both

set -g pane-active-border-style bg=default,fg=magenta

# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
set-window-option -g pane-base-index 1

# option for autoread
set-option -g focus-events on

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# status bar
set-option -g status-position bottom
set-option -g status-justify centre
set -g status-style bg=default
set -g status-left ''
set -g status-right "#[fg=red][#S]"

# highlight current window
set -g window-status-current-style fg=black,bg=brightmagenta

set-window-option -g automatic-rename off
set-option -g allow-rename off

# increase scrollback lines
set -g history-limit 10000

# switch to last pane
bind-key C-a last-pane

# bind a reload key
bind R source-file ~/.config/tmux/tmux.conf \; display-message " Config reloaded..".

# Local config
if-shell "[ -f ~/.tmux.conf.local ]" 'source ~/.tmux.conf.local'

# tpm
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
